#include "images.h"

const ext_img_desc_t images[34] = {
    { "ma_a", &img_ma_a },
    { "ma_b", &img_ma_b },
    { "ma_c", &img_ma_c },
    { "ma_e", &img_ma_e },
    { "ma_f", &img_ma_f },
    { "ma_g", &img_ma_g },
    { "ma_h", &img_ma_h },
    { "ma_i", &img_ma_i },
    { "ma_j", &img_ma_j },
    { "ma_k", &img_ma_k },
    { "ma_l", &img_ma_l },
    { "ma_m", &img_ma_m },
    { "ma_n", &img_ma_n },
    { "ma_o", &img_ma_o },
    { "ma_p", &img_ma_p },
    { "ma_q", &img_ma_q },
    { "ma_r", &img_ma_r },
    { "ma_s1", &img_ma_s1 },
    { "ma_s2", &img_ma_s2 },
    { "ma_s3", &img_ma_s3 },
    { "ma_s4", &img_ma_s4 },
    { "defaul1", &img_defaul1 },
    { "defaul2", &img_defaul2 },
    { "defaul3", &img_defaul3 },
    { "defaul4", &img_defaul4 },
    { "ma_not", &img_ma_not },
    { "mode1", &img_mode1 },
    { "mode2", &img_mode2 },
    { "sewing_data", &img_sewing_data },
    { "check_program", &img_check_program },
    { "register_sewing_data_custom", &img_register_sewing_data_custom },
    { "register_the_pattern", &img_register_the_pattern },
    { "change_sewing_mode", &img_change_sewing_mode },
    { "performing_format", &img_performing_format },
};